# Generated by Django 5.0.3 on 2024-09-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='images',
            field=models.ImageField(null=True, upload_to='templates'),
        ),
    ]
