# Generated by Django 5.0.3 on 2024-09-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='images',
            field=models.URLField(null=True),
        ),
    ]
